version: 0.2

phases:
  build:
    commands:
      - echo "Detecting changed Lambda functions..."
      - |
        CHANGED_FUNCTIONS=$(git diff --name-only HEAD~1 HEAD | awk -F'/' '{print $1}' | sort -u)
        echo "Changed functions: $CHANGED_FUNCTIONS"

        for function in $CHANGED_FUNCTIONS; do
          if [[ -d "$function" ]]; then
            echo "Updating code for $function..."
            cd $function
            zip -r ../$function.zip lambda_function.py  # Only zip the handler file
            aws lambda update-function-code --function-name $function --zip-file fileb://../$function.zip
            cd ..
          fi
        done
  post_build:
    commands:
      - echo "Deployment completed!"

artifacts:
  files:
    - '**/*'
